name: build-qb64
run-name: ${{ github.actor }} building qb64 executable
on: [push]
jobs:
  installs-qb64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: wget https://github.com/QB64Official/qb64/releases/download/v2.1/qb64_dev_2022-09-08-07-14-00_47f5044_lnx.tar.gz
