name: build-qb64
run-name: ${{ github.actor }} building qb64 executable
on: [push]
jobs:
  download-and-install-qb64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download QB64
        run: curl  -L -o ./qb64_lnx.tgz.gz https://github.com/QB64Official/qb64/releases/download/v2.1/qb64_dev_2022-09-08-07-14-00_47f5044_lnx.tar.gz
      - name: Unzip QB64
        run: tar -xf ./qb64_lnx.tgz.gz
      - name: Rename QB64 folder
        run: mv ./qb64_2022-09-08-23-38-12_47f5044_lnx ./qb64
      - name: Run Linux setup script
        run: ./qb64/setup_lnx.sh
      - name: Create test file
        run: echo "PRINT 51" > ./test.bas
      - name: List files
        run: ls -al
      - name: Try test compile
        run: ./run_qb64.sh -c ./test.bas
      - name: List files
        run: ls -al
